/**
 * Canonical permission catalogue (specification §2.3). Single source of
 * truth for the global `permissions` table: seeding is additive and idempotent
 * (migrator side); route guards reference these codes; role templates map
 * roles to explicit permission lists (no wildcards at grant time — §2.3:
 * "the actual grants are explicit rows, so a role diff is always readable").
 */
export const PERMISSION_CATALOGUE: Readonly<Record<string, string>> = Object.freeze({
  // platform.*
  "platform.tenant.read": "List tenants (console)",
  "platform.tenant.create": "Create tenants",
  "platform.tenant.update": "Update tenant metadata",
  "platform.tenant.suspend": "Suspend/reactivate tenants",
  "platform.tenant.export": "Trigger tenant export",
  "platform.tenant.offboard": "Trigger offboard purge",
  "platform.admin.read": "List tenant admins",
  "platform.admin.create": "Create tenant admins",
  "platform.admin.reset": "Reset tenant admin credentials",
  "platform.user.read": "List platform users",
  "platform.module.read": "Read module entitlements",
  "platform.module.update": "Enable/disable modules",
  "platform.module.preflight": "Run module preflight",
  "platform.plan.read": "Read subscription plans",
  "platform.plan.create": "Create plans",
  "platform.plan.update": "Update plans",
  "platform.plan.change": "Change a tenant's plan",
  "platform.flag.write": "Write feature flags",
  "platform.announcement.read": "Read announcements",
  "platform.announcement.create": "Create announcements",
  "platform.announcement.update": "Update announcements",
  "platform.settings.read": "Read system settings",
  "platform.settings.write": "Write system settings",
  "platform.security.read": "Read security events",
  "platform.job.read": "Read job runs",
  "platform.report.view": "View platform reports",
  "platform.breakglass.enter": "Enter a tenant break-glass session",
  "platform.breakglass.read": "Read break-glass sessions",

  // admin.*
  "admin.branch.read": "View branches",
  "admin.branch.create": "Create branches",
  "admin.branch.update": "Update branches",
  "admin.branch.delete": "Archive branches",
  "admin.user.read": "View users",
  "admin.user.create": "Invite users",
  "admin.user.update": "Update users",
  "admin.user.deactivate": "Deactivate users",
  "admin.user.reset": "Reset user passwords/MFA",
  "admin.role.read": "View roles and permission matrix",
  "admin.role.create": "Create roles",
  "admin.role.update": "Edit roles and permissions",
  "admin.role.delete": "Delete roles",
  "admin.module.read": "See own tenant's entitlements (read-only)",
  "admin.practitioner.read": "View practitioners",
  "admin.practitioner.create": "Create practitioners",
  "admin.practitioner.update": "Update practitioners",
  "admin.practitioner.delete": "Deactivate practitioners",
  "admin.service_unit.read": "View service units",
  "admin.service_unit.create": "Create service units",
  "admin.service_unit.update": "Update service units",
  "admin.service_unit.delete": "Delete service units",
  "admin.service.read": "View service catalogue",
  "admin.service.create": "Create services",
  "admin.service.update": "Update services",
  "admin.service.delete": "Delete services",
  "admin.price.read": "View price lists",
  "admin.price.create": "Create prices",
  "admin.price.update": "Update prices",
  "admin.price.delete": "Delete prices",
  "admin.discount.read": "View discount types",
  "admin.discount.create": "Create discount types",
  "admin.discount.update": "Update discount types",
  "admin.discount.delete": "Delete discount types",
  "admin.payment_method.read": "View payment methods",
  "admin.payment_method.create": "Create payment methods",
  "admin.payment_method.update": "Update payment methods",
  "admin.payment_method.delete": "Delete payment methods",
  "admin.schedule.read": "View schedules",
  "admin.schedule.update": "Edit schedule templates",
  "admin.template.read": "View templates",
  "admin.template.create": "Create templates",
  "admin.template.update": "Update templates",
  "admin.settings.read": "Read tenant settings",
  "admin.settings.update": "Change tenant settings",
  "admin.apikey.read": "View API keys",
  "admin.apikey.create": "Create API keys",
  "admin.apikey.update": "Rotate API keys",
  "admin.apikey.delete": "Revoke API keys",

  // patient.*
  "patient.record.create": "Register patients",
  "patient.record.read": "View patient records",
  "patient.record.update": "Edit patient records",
  "patient.record.merge": "Merge duplicate patients",
  "patient.record.restricted_read": "View restricted patients (ABAC)",
  "patient.record.read_sensitive": "Reveal masked identifiers",
  "patient.document.read": "View patient documents",
  "patient.document.create": "Upload patient documents",
  "patient.document.delete": "Archive patient documents",

  // clinical.*
  "clinical.schedule.read": "View schedules",
  "clinical.schedule.update": "Edit own schedule",
  "clinical.appointment.read": "View appointments",
  "clinical.appointment.create": "Book appointments",
  "clinical.appointment.update": "Reschedule appointments",
  "clinical.appointment.cancel": "Cancel appointments",
  "clinical.appointment.no_show": "Mark no-shows",
  "clinical.queue.read": "View the queue board",
  "clinical.queue.call": "Call next patient",
  "clinical.queue.skip": "Skip a queue entry",
  "clinical.queue.recall": "Recall a queue entry",
  "clinical.queue.complete": "Complete a queue entry",
  "clinical.visit.read": "View visits",
  "clinical.visit.create": "Open visits",
  "clinical.visit.update": "Edit visits",
  "clinical.visit.start": "Start a consultation",
  "clinical.visit.ready": "Mark a visit ready for billing",
  "clinical.visit.close": "Close a visit",
  "clinical.visit.cancel": "Cancel a visit",
  "clinical.vitals.read": "View vitals",
  "clinical.vitals.create": "Record vitals",
  "clinical.vitals.update": "Edit vitals",
  "clinical.note.read": "View clinical notes",
  "clinical.note.create": "Write clinical notes",
  "clinical.note.update": "Edit draft notes",
  "clinical.note.sign": "Sign clinical notes",
  "clinical.note.amend": "Amend signed notes",
  "clinical.diagnosis.read": "View diagnoses",
  "clinical.diagnosis.create": "Record diagnoses",
  "clinical.diagnosis.update": "Edit diagnoses",
  "clinical.diagnosis.delete": "Remove diagnoses",
  "clinical.procedure.read": "View procedures",
  "clinical.procedure.create": "Record procedures",
  "clinical.procedure.update": "Edit procedures",
  "clinical.procedure.delete": "Remove procedures",
  "clinical.supply.read": "View supplies used",
  "clinical.supply.create": "Record supply usage",
  "clinical.supply.void": "Void supply usage",
  "clinical.certificate.read": "View certificates",
  "clinical.certificate.create": "Issue certificates",
  "clinical.certificate.void": "Void certificates",
  "clinical.referral.read": "View referrals",
  "clinical.referral.create": "Create referrals",
  "clinical.referral.update": "Edit referrals",
  "clinical.referral.delete": "Delete referrals",
  "clinical.immunization.read": "View immunizations",
  "clinical.immunization.create": "Record immunizations",
  "clinical.immunization.delete": "Void immunizations",
  "clinical.problem.read": "View problems",
  "clinical.problem.create": "Record problems",
  "clinical.problem.update": "Edit problems",
  "clinical.problem.resolve": "Resolve problems",
  "clinical.rx.read": "View prescriptions",
  "clinical.rx.create": "Create prescriptions",
  "clinical.rx.update": "Edit draft prescriptions",
  "clinical.rx.sign": "Sign/issue prescriptions",
  "clinical.rx.cancel": "Cancel prescriptions",
  "clinical.order_set.read": "View order sets",
  "clinical.order_set.create": "Create order sets",
  "clinical.order_set.update": "Edit order sets",
  "clinical.order_set.delete": "Delete order sets",
  "clinical.template.read": "View note templates",
  "clinical.template.create": "Create note templates",
  "clinical.template.update": "Edit note templates",
  "clinical.template.delete": "Delete note templates",

  // lab.*
  "lab.config.read": "View lab configuration",
  "lab.config.create": "Create lab configuration",
  "lab.config.update": "Update lab configuration",
  "lab.config.delete": "Delete lab configuration",
  "lab.order.read": "View lab orders",
  "lab.order.create": "Order tests",
  "lab.order.update": "Edit lab orders",
  "lab.order.cancel": "Cancel lab orders",
  "lab.specimen.read": "View specimens",
  "lab.specimen.collect": "Collect specimens",
  "lab.specimen.receive": "Receive specimens",
  "lab.specimen.reject": "Reject specimens",
  "lab.result.read": "View results",
  "lab.result.enter": "Enter results",
  "lab.result.verify": "Verify results",
  "lab.result.amend": "Amend released results",
  "lab.result.view_confidential": "View confidential results",
  "lab.critical.read": "See critical values",
  "lab.critical.ack": "Acknowledge critical values",
  "lab.report.read": "View lab reports",
  "lab.report.release": "Release lab reports",
  "lab.qc.read": "View QC",
  "lab.qc.create": "Run QC",
  "lab.qc.update": "Edit QC",
  "lab.qc.accept": "Accept QC runs",
  "lab.qc.reject": "Reject QC runs",
  "lab.sendout.read": "View send-outs",
  "lab.sendout.create": "Create send-outs",
  "lab.sendout.update": "Update send-outs",
  "lab.interface.read": "View interface queue",
  "lab.interface.write": "Reprocess interface messages",
  "lab.tat.read": "View TAT dashboard",

  // pharmacy.*
  "pharmacy.rx.read": "View the verification queue",
  "pharmacy.rx.verify": "Verify prescriptions",
  "pharmacy.rx.intervene": "Intervene on prescriptions",
  "pharmacy.dispense.read": "View dispenses",
  "pharmacy.dispense.create": "Prepare dispenses",
  "pharmacy.dispense.update": "Edit dispenses",
  "pharmacy.dispense.post": "Post dispenses",
  "pharmacy.dispense.void": "Void dispenses",
  "pharmacy.sale.read": "View OTC sales",
  "pharmacy.sale.create": "Start OTC sales",
  "pharmacy.sale.post": "Post OTC sales",
  "pharmacy.return.read": "View returns",
  "pharmacy.return.create": "Create returns",
  "pharmacy.return.post": "Post returns",
  "pharmacy.product.read": "View products",
  "pharmacy.product.create": "Create products",
  "pharmacy.product.update": "Update products",
  "pharmacy.product.delete": "Delete products",
  "pharmacy.price.read": "View pharmacy prices",
  "pharmacy.price.create": "Create pharmacy prices",
  "pharmacy.price.update": "Update pharmacy prices",
  "pharmacy.price.delete": "Delete pharmacy prices",
  "pharmacy.controlled.read": "View the controlled register",
  "pharmacy.controlled.write": "Write controlled entries",
  "pharmacy.controlled.witness": "Witness controlled dispensing",
  "pharmacy.controlled.dispense": "Dispense controlled drugs",
  "pharmacy.controlled.report": "Generate controlled reports",
  "pharmacy.stock.read": "View pharmacy stock",
  "pharmacy.admin.create": "Record in-clinic administration",
  "pharmacy.report.view": "View pharmacy reports",

  // supply.*
  "supply.item.read": "View items",
  "supply.item.create": "Create items",
  "supply.item.update": "Update items",
  "supply.item.delete": "Delete items",
  "supply.supplier.read": "View suppliers",
  "supply.supplier.create": "Create suppliers",
  "supply.supplier.update": "Update suppliers",
  "supply.supplier.delete": "Delete suppliers",
  "supply.location.read": "View locations",
  "supply.location.create": "Create locations",
  "supply.location.update": "Update locations",
  "supply.location.delete": "Delete locations",
  "supply.pr.read": "View purchase requests",
  "supply.pr.create": "Create purchase requests",
  "supply.pr.update": "Edit purchase requests",
  "supply.pr.submit": "Submit purchase requests",
  "supply.pr.approve": "Approve purchase requests",
  "supply.pr.reject": "Reject purchase requests",
  "supply.pr.cancel": "Cancel purchase requests",
  "supply.pr.convert": "Convert PRs to POs",
  "supply.po.read": "View purchase orders",
  "supply.po.create": "Create purchase orders",
  "supply.po.update": "Edit purchase orders",
  "supply.po.submit": "Submit purchase orders",
  "supply.po.approve": "Approve purchase orders",
  "supply.po.reject": "Reject purchase orders",
  "supply.po.send": "Send purchase orders",
  "supply.po.close": "Close purchase orders",
  "supply.po.cancel": "Cancel purchase orders",
  "supply.grn.read": "View receipts",
  "supply.grn.create": "Create receipts",
  "supply.grn.update": "Edit receipts",
  "supply.grn.post": "Post receipts",
  "supply.grn.void": "Void receipts",
  "supply.invoice.read": "View supplier invoices",
  "supply.invoice.create": "Create supplier invoices",
  "supply.invoice.update": "Edit supplier invoices",
  "supply.invoice.match": "3-way match supplier invoices",
  "supply.return.read": "View supplier returns",
  "supply.return.create": "Create supplier returns",
  "supply.return.post": "Post supplier returns",
  "supply.return.close": "Close supplier returns",
  "supply.req.read": "View requisitions",
  "supply.req.create": "Create requisitions",
  "supply.req.update": "Edit requisitions",
  "supply.req.submit": "Submit requisitions",
  "supply.req.approve": "Approve requisitions",
  "supply.req.reject": "Reject requisitions",
  "supply.req.cancel": "Cancel requisitions",
  "supply.req.receive": "Receive issued stock",
  "supply.issue.read": "View issues",
  "supply.issue.create": "Create issues",
  "supply.issue.update": "Edit issues",
  "supply.issue.post": "Post issues",
  "supply.transfer.read": "View transfers",
  "supply.transfer.create": "Create transfers",
  "supply.transfer.post": "Post transfers",
  "supply.transfer.receive": "Receive transfers",
  "supply.adjust.read": "View adjustments",
  "supply.adjust.create": "Create adjustments",
  "supply.adjust.submit": "Submit adjustments",
  "supply.adjust.approve": "Approve adjustments",
  "supply.adjust.reject": "Reject adjustments",
  "supply.adjust.post": "Post adjustments",
  "supply.adjust.void": "Void adjustments",
  "supply.count.read": "View counts",
  "supply.count.create": "Create counts",
  "supply.count.update": "Enter counts",
  "supply.count.recount": "Request recounts",
  "supply.count.submit": "Submit counts",
  "supply.count.approve": "Approve counts",
  "supply.count.post": "Post counts",
  "supply.dispose.read": "View disposals",
  "supply.dispose.create": "Create disposals",
  "supply.dispose.post": "Post disposals",
  "supply.dispose.witness": "Witness disposals",
  "supply.dispose.certificate": "Issue disposal certificates",
  "supply.recall.read": "View recalls",
  "supply.recall.create": "Create recalls",
  "supply.recall.quarantine": "Quarantine recalled lots",
  "supply.recall.close": "Close recalls",
  "supply.batch.quarantine": "Quarantine batches",
  "supply.batch.release": "Release quarantined batches",
  "supply.stock.read": "View stock balances",
  "supply.consumption.create": "Post consumption",
  "supply.period.lock": "Lock periods",
  "supply.period.unlock": "Unlock periods",
  "supply.report.view": "View supply reports",

  // billing.*
  "billing.invoice.read": "View invoices",
  "billing.invoice.create": "Create invoices",
  "billing.invoice.update": "Edit invoices",
  "billing.invoice.void": "Void invoices",
  "billing.charge.create": "Post charge-capture lines",
  "billing.payment.read": "View payments",
  "billing.payment.create": "Take payments",
  "billing.payment.void": "Void payments",
  "billing.credit.read": "View credit notes",
  "billing.credit.create": "Create credit notes",
  "billing.credit.approve": "Approve credit notes",
  "billing.shift.read": "View shifts",
  "billing.shift.open": "Open shifts",
  "billing.shift.close": "Close shifts",
  "billing.discount.read": "View discounts",
  "billing.discount.create": "Apply discounts",
  "billing.discount.revoke": "Revoke discounts",

  // compliance.*
  "compliance.audit.read": "Read the audit trail",
  "compliance.access.read": "Read PHI access logs",
  "compliance.consent.read": "View consents",
  "compliance.consent.create": "Capture consents",
  "compliance.consent.update": "Update consents",
  "compliance.consent.write": "Publish consent templates",
  "compliance.dsr.read": "View DSR requests",
  "compliance.dsr.create": "Intake DSR requests",
  "compliance.dsr.verify": "Verify DSR identity",
  "compliance.dsr.start": "Start DSR processing",
  "compliance.dsr.complete": "Complete DSR requests",
  "compliance.dsr.reject": "Reject DSR requests",
  "compliance.dsr.extend": "Extend DSR deadlines",
  "compliance.breach.read": "View breaches",
  "compliance.breach.create": "Register breaches",
  "compliance.breach.update": "Update breaches",
  "compliance.breach.assess": "Assess breaches",
  "compliance.breach.notify": "Send breach notifications",
  "compliance.breach.close": "Close breaches",
  "compliance.retention.read": "View retention policies",
  "compliance.retention.create": "Create retention policies",
  "compliance.retention.update": "Update retention policies",
  "compliance.retention.enforce": "Enforce retention",
  "compliance.hold.read": "View legal holds",
  "compliance.hold.create": "Create legal holds",
  "compliance.hold.release": "Release legal holds",
  "compliance.access_review.read": "View access reviews",
  "compliance.access_review.create": "Start access reviews",
  "compliance.access_review.decide": "Record access review decisions",

  // cross-cutting
  "reference.read": "Read reference data",
  "files.read": "Download files",
  "files.write": "Upload files",
  "jobs.read": "View job runs",
  "jobs.cancel": "Cancel/replay jobs",
  "notifications.read": "Read notifications",
  "notifications.send": "Send notifications",
});

/** Explicit system-role templates (§2.2). Wildcards resolved to rows. */
export const SYSTEM_ROLE_TEMPLATES: Readonly<Record<string, readonly string[]>> = Object.freeze({
  tenant_admin: [
    "admin.branch.read", "admin.branch.create", "admin.branch.update", "admin.branch.delete",
    "admin.user.read", "admin.user.create", "admin.user.update", "admin.user.deactivate", "admin.user.reset",
    "admin.role.read", "admin.role.create", "admin.role.update", "admin.role.delete",
    "admin.module.read",
    "admin.practitioner.read", "admin.practitioner.create", "admin.practitioner.update", "admin.practitioner.delete",
    "admin.service_unit.read", "admin.service_unit.create", "admin.service_unit.update", "admin.service_unit.delete",
    "admin.service.read", "admin.service.create", "admin.service.update", "admin.service.delete",
    "admin.price.read", "admin.price.create", "admin.price.update", "admin.price.delete",
    "admin.discount.read", "admin.discount.create", "admin.discount.update", "admin.discount.delete",
    "admin.payment_method.read", "admin.payment_method.create", "admin.payment_method.update", "admin.payment_method.delete",
    "admin.schedule.read", "admin.schedule.update",
    "admin.template.read", "admin.template.create", "admin.template.update",
    "admin.settings.read", "admin.settings.update",
    "admin.apikey.read", "admin.apikey.create", "admin.apikey.update", "admin.apikey.delete",
    "patient.record.create", "patient.record.read", "patient.record.update",
    "patient.document.read", "patient.document.create", "patient.document.delete",
    "clinical.schedule.read", "clinical.appointment.read",
    "clinical.visit.read", "clinical.vitals.read",
    "compliance.audit.read", "compliance.access.read",
    "reference.read", "files.read", "files.write", "jobs.read", "notifications.read", "notifications.send",
  ],
  branch_manager: [
    "admin.branch.read", "admin.user.read", "admin.role.read", "admin.module.read",
    "patient.record.create", "patient.record.read", "patient.record.update",
    "clinical.schedule.read", "clinical.schedule.update",
    "clinical.appointment.read", "clinical.appointment.update", "clinical.appointment.cancel", "clinical.appointment.no_show",
    "clinical.queue.read", "clinical.queue.call", "clinical.queue.skip", "clinical.queue.recall", "clinical.queue.complete",
    "clinical.visit.read", "clinical.visit.cancel",
    "clinical.note.read",
    "lab.order.read", "pharmacy.rx.read", "supply.stock.read", "pharmacy.stock.read",
    "billing.invoice.read", "billing.shift.read",
    "supply.pr.approve", "supply.req.approve",
    "reference.read", "files.read", "notifications.read",
  ],
  doctor: [
    "patient.record.read", "patient.record.update",
    "clinical.schedule.read", "clinical.schedule.update",
    "clinical.appointment.read", "clinical.appointment.update",
    "clinical.queue.read",
    "clinical.visit.read", "clinical.visit.create", "clinical.visit.update", "clinical.visit.start", "clinical.visit.ready", "clinical.visit.close",
    "clinical.vitals.read", "clinical.vitals.create", "clinical.vitals.update",
    "clinical.note.read", "clinical.note.create", "clinical.note.update", "clinical.note.sign", "clinical.note.amend",
    "clinical.diagnosis.read", "clinical.diagnosis.create", "clinical.diagnosis.update", "clinical.diagnosis.delete",
    "clinical.procedure.read", "clinical.procedure.create", "clinical.procedure.update", "clinical.procedure.delete",
    "clinical.supply.read", "clinical.supply.create",
    "clinical.certificate.read", "clinical.certificate.create",
    "clinical.referral.read", "clinical.referral.create", "clinical.referral.update",
    "clinical.problem.read", "clinical.problem.create", "clinical.problem.update", "clinical.problem.resolve",
    "clinical.rx.read", "clinical.rx.create", "clinical.rx.update", "clinical.rx.sign", "clinical.rx.cancel",
    "clinical.order_set.read", "clinical.order_set.create", "clinical.order_set.update",
    "clinical.template.read", "clinical.template.create", "clinical.template.update",
    "clinical.immunization.read", "clinical.immunization.create",
    "lab.order.read", "lab.order.create", "lab.result.read", "lab.report.read",
    "pharmacy.rx.read",
    "reference.read", "files.read", "files.write", "notifications.read",
  ],
  nurse: [
    "patient.record.read",
    "clinical.schedule.read", "clinical.appointment.read", "clinical.appointment.create", "clinical.appointment.update",
    "clinical.queue.read", "clinical.queue.call", "clinical.queue.skip",
    "clinical.visit.read", "clinical.visit.create", "clinical.visit.update",
    "clinical.vitals.read", "clinical.vitals.create", "clinical.vitals.update",
    "clinical.note.read", "clinical.note.create", "clinical.note.update",
    "clinical.procedure.read", "clinical.procedure.create",
    "clinical.supply.read", "clinical.supply.create",
    "clinical.immunization.read", "clinical.immunization.create",
    "lab.specimen.collect",
    "supply.req.read", "supply.req.create", "supply.consumption.create",
    "pharmacy.admin.create",
    "reference.read", "files.read", "notifications.read",
  ],
  encoder: [
    "patient.record.create", "patient.record.read", "patient.record.update",
    "patient.document.read", "patient.document.create",
    "clinical.schedule.read", "clinical.schedule.update",
    "clinical.appointment.read", "clinical.appointment.create", "clinical.appointment.update", "clinical.appointment.cancel",
    "clinical.queue.read", "clinical.queue.call", "clinical.queue.complete",
    "clinical.visit.read", "clinical.visit.create",
    "clinical.vitals.read", "clinical.vitals.create",
    "lab.order.read", "lab.order.create", "lab.result.enter",
    "billing.charge.create",
    "reference.read", "notifications.read",
  ],
  cashier: [
    "patient.record.read",
    "billing.invoice.read", "billing.invoice.create", "billing.invoice.update",
    "billing.payment.read", "billing.payment.create",
    "billing.credit.read", "billing.credit.create",
    "billing.shift.read", "billing.shift.open", "billing.shift.close",
    "billing.discount.read", "billing.discount.create",
    "clinical.visit.read",
    "reference.read", "notifications.read",
  ],
  pharmacist: [
    "patient.record.read",
    "clinical.rx.read", "clinical.visit.read",
    "pharmacy.rx.read", "pharmacy.rx.verify", "pharmacy.rx.intervene",
    "pharmacy.dispense.read", "pharmacy.dispense.create", "pharmacy.dispense.update", "pharmacy.dispense.post", "pharmacy.dispense.void",
    "pharmacy.sale.read", "pharmacy.sale.create", "pharmacy.sale.post",
    "pharmacy.return.read", "pharmacy.return.create", "pharmacy.return.post",
    "pharmacy.controlled.read", "pharmacy.controlled.write", "pharmacy.controlled.witness", "pharmacy.controlled.dispense", "pharmacy.controlled.report",
    "pharmacy.stock.read", "pharmacy.product.read", "pharmacy.price.read",
    "supply.req.read", "supply.req.create",
    "pharmacy.report.view",
    "reference.read", "files.read", "notifications.read",
  ],
  pharmacy_assistant: [
    "patient.record.read",
    "clinical.rx.read",
    "pharmacy.rx.read",
    "pharmacy.dispense.read", "pharmacy.dispense.create", "pharmacy.dispense.update",
    "pharmacy.sale.read", "pharmacy.sale.create", "pharmacy.sale.post",
    "pharmacy.stock.read", "pharmacy.product.read",
    "reference.read", "notifications.read",
  ],
  phlebotomist: [
    "patient.record.read",
    "lab.order.read", "lab.specimen.read", "lab.specimen.collect",
    "reference.read", "notifications.read",
  ],
  medtech: [
    "patient.record.read",
    "lab.order.read", "lab.specimen.read", "lab.specimen.receive", "lab.specimen.reject",
    "lab.result.read", "lab.result.enter",
    "lab.qc.read", "lab.qc.create", "lab.qc.update",
    "supply.req.read", "supply.req.create",
    "reference.read", "notifications.read",
  ],
  lab_manager: [
    "lab.config.read", "lab.config.create", "lab.config.update", "lab.config.delete",
    "lab.order.read", "lab.specimen.read", "lab.specimen.receive", "lab.specimen.reject",
    "lab.result.read", "lab.result.verify", "lab.result.amend",
    "lab.qc.read", "lab.qc.create", "lab.qc.update", "lab.qc.accept", "lab.qc.reject",
    "lab.critical.read", "lab.critical.ack",
    "lab.report.read", "lab.report.release",
    "lab.sendout.read", "lab.sendout.create", "lab.sendout.update",
    "lab.tat.read",
    "supply.req.read", "supply.req.create", "supply.stock.read",
    "reference.read", "notifications.read",
  ],
  pathologist: [
    "patient.record.read",
    "lab.order.read", "lab.result.read", "lab.result.verify", "lab.result.amend", "lab.result.view_confidential",
    "lab.report.read", "lab.report.release",
    "lab.critical.read", "lab.critical.ack",
    "reference.read", "notifications.read",
  ],
  supply_officer: [
    "supply.item.read", "supply.item.create", "supply.item.update", "supply.item.delete",
    "supply.supplier.read",
    "supply.location.read", "supply.location.create", "supply.location.update", "supply.location.delete",
    "supply.req.read", "supply.req.approve",
    "supply.issue.read", "supply.issue.create", "supply.issue.update", "supply.issue.post",
    "supply.grn.read", "supply.grn.create", "supply.grn.update", "supply.grn.post",
    "supply.count.read", "supply.count.create", "supply.count.update", "supply.count.recount", "supply.count.submit", "supply.count.approve", "supply.count.post",
    "supply.adjust.read", "supply.adjust.create",
    "supply.dispose.read", "supply.dispose.create", "supply.dispose.post",
    "supply.recall.read", "supply.recall.create", "supply.recall.quarantine", "supply.recall.close",
    "supply.batch.quarantine", "supply.batch.release",
    "supply.stock.read", "supply.consumption.create", "supply.report.view",
    "reference.read", "notifications.read",
  ],
  purchaser: [
    "supply.supplier.read", "supply.supplier.create", "supply.supplier.update", "supply.supplier.delete",
    "supply.pr.read", "supply.pr.create", "supply.pr.update", "supply.pr.submit", "supply.pr.convert",
    "supply.po.read", "supply.po.create", "supply.po.update", "supply.po.submit", "supply.po.send", "supply.po.close",
    "supply.invoice.read", "supply.invoice.create", "supply.invoice.update",
    "supply.stock.read",
    "reference.read", "notifications.read",
  ],
  auditor: [
    "admin.branch.read", "admin.user.read", "admin.role.read", "admin.module.read",
    "compliance.audit.read", "compliance.access.read",
    "reference.read",
  ],
  dpo: [
    "admin.user.read",
    "compliance.audit.read", "compliance.access.read",
    "compliance.consent.read", "compliance.consent.create", "compliance.consent.update", "compliance.consent.write",
    "compliance.dsr.read", "compliance.dsr.create", "compliance.dsr.verify", "compliance.dsr.start",
    "compliance.dsr.complete", "compliance.dsr.reject", "compliance.dsr.extend",
    "compliance.breach.read", "compliance.breach.create", "compliance.breach.update", "compliance.breach.assess", "compliance.breach.notify", "compliance.breach.close",
    "compliance.retention.read", "compliance.retention.create", "compliance.retention.update",
    "compliance.hold.read", "compliance.hold.create", "compliance.hold.release",
    "compliance.access_review.read", "compliance.access_review.create", "compliance.access_review.decide",
    "patient.record.read",
    "reference.read",
  ],
});

/** Every catalogue code (validation that templates stay in-catalogue). */
export const ALL_PERMISSIONS: readonly string[] = Object.keys(PERMISSION_CATALOGUE);
